/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaponto;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author bthez
 */
public class TelaPonto extends javax.swing.JFrame {

    /**
     * Creates new form TelaPonto
     */
    
    public TelaPonto() {
        initComponents();
    }
    
    public TelaPonto(String nome){
        initComponents();
        setLocationRelativeTo(null);
        nomeLabel.setText(nome);
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime dataAtual = LocalDateTime.now();
        var dataFormatada = dateFormat.format(dataAtual);
        dataLabel.setText(dataFormatada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entradaManhaButton = new javax.swing.JButton();
        saidaManhaButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        entradaTardeButton = new javax.swing.JButton();
        saidaTardeButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        entradaNoiteButton = new javax.swing.JButton();
        saidaNoiteButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Manhã");

        entradaManhaButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        entradaManhaButton.setText("Entrada");
        entradaManhaButton.setBorderPainted(false);
        entradaManhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaManhaButtonActionPerformed(evt);
            }
        });

        saidaManhaButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        saidaManhaButton.setText("Saída");
        saidaManhaButton.setBorderPainted(false);
        saidaManhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaManhaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(entradaManhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(saidaManhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saidaManhaButton)
                    .addComponent(entradaManhaButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Tarde");

        entradaTardeButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        entradaTardeButton.setText("Entrada");
        entradaTardeButton.setBorderPainted(false);
        entradaTardeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTardeButtonActionPerformed(evt);
            }
        });

        saidaTardeButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        saidaTardeButton.setText("Saída");
        saidaTardeButton.setBorderPainted(false);
        saidaTardeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaTardeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(entradaTardeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(saidaTardeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saidaTardeButton)
                    .addComponent(entradaTardeButton))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(180, 100));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Noite");

        entradaNoiteButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        entradaNoiteButton.setText("Entrada");
        entradaNoiteButton.setBorderPainted(false);
        entradaNoiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaNoiteButtonActionPerformed(evt);
            }
        });

        saidaNoiteButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        saidaNoiteButton.setText("Saída");
        saidaNoiteButton.setBorderPainted(false);
        saidaNoiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaNoiteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(entradaNoiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(saidaNoiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saidaNoiteButton)
                    .addComponent(entradaNoiteButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel7.setText("Folha Ponto");

        nomeLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nomeLabel.setText("usuario");

        dataLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dataLabel.setText("data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeLabel)
                    .addComponent(dataLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeLabel)
                .addGap(55, 55, 55)
                .addComponent(dataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaManhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaManhaButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de entrada(Manha)" + horaFormatada);
        
        entradaManhaButton.setEnabled(false);
        
    }//GEN-LAST:event_entradaManhaButtonActionPerformed

    private void saidaManhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaManhaButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de saida(Manha)" + horaFormatada);
        
        saidaManhaButton.setEnabled(false);
    }//GEN-LAST:event_saidaManhaButtonActionPerformed

    private void entradaTardeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaTardeButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de entrada(Tarde)" + horaFormatada);
        
        entradaTardeButton.setEnabled(false);
    }//GEN-LAST:event_entradaTardeButtonActionPerformed

    private void saidaTardeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaTardeButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de saida(Tarde)" + horaFormatada);
        
        saidaTardeButton.setEnabled(false);
    }//GEN-LAST:event_saidaTardeButtonActionPerformed

    private void entradaNoiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaNoiteButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de entrada(Noite)" + horaFormatada);
        
        entradaNoiteButton.setEnabled(false);
    }//GEN-LAST:event_entradaNoiteButtonActionPerformed

    private void saidaNoiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaNoiteButtonActionPerformed
        DateTimeFormatter horaFormat = DateTimeFormatter.ofPattern("HH:mm");
        LocalDateTime horaAtual = LocalDateTime.now();
        var horaFormatada = horaFormat.format(horaAtual);
        
        System.out.println("Horario de saida(Noite)" + horaFormatada);
        
        saidaNoiteButton.setEnabled(false);
    }//GEN-LAST:event_saidaNoiteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPonto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private javax.swing.JButton entradaManhaButton;
    private javax.swing.JButton entradaNoiteButton;
    private javax.swing.JButton entradaTardeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton saidaManhaButton;
    private javax.swing.JButton saidaNoiteButton;
    private javax.swing.JButton saidaTardeButton;
    // End of variables declaration//GEN-END:variables
}
